# baseURL = "http://localhost"
title = "Cooking"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true


# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   category = "categories"
   time = "time"
   tag = "tags"

[params]
# Show a breadcrumb navigation bar at the top of each docs page.
geekdocBreadcrumb = true
